-- =====================================================
-- FASE 3: Catálogo Normalizado de Temas
-- Generado desde docs/categorias.json (248 temas)
-- =====================================================

-- Temas normalizados (reemplaza texto libre)
CREATE TABLE IF NOT EXISTS quipu_categorias (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    nombre_normalizado VARCHAR(100),  -- Sin tildes, lowercase para matching
    categoria VARCHAR(50),            -- 'economia', 'social', 'seguridad', 'politica'
    sector VARCHAR(100),              -- 'seguros', 'mineria', 'salud' (para filtrar por gremio)
    keywords TEXT[],                  -- ['AFP', 'ONP', 'jubilación'] para auto-mapping
    descripcion TEXT,
    icono VARCHAR(50),
    color VARCHAR(20),
    orden INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Temas prioritarios por cliente
CREATE TABLE IF NOT EXISTS quipu_cliente_categorias (
    cliente_id INTEGER REFERENCES quipu_clientes(id) ON DELETE CASCADE,
    tema_id INTEGER REFERENCES quipu_categorias(id) ON DELETE CASCADE,
    prioridad INTEGER DEFAULT 1,      -- 1=alta, 2=media, 3=baja
    alertas_activas BOOLEAN DEFAULT TRUE,
    keywords_custom TEXT[],           -- Keywords adicionales del cliente
    added_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (cliente_id, tema_id)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_temas_sector ON quipu_categorias(sector);
CREATE INDEX IF NOT EXISTS idx_temas_categoria ON quipu_categorias(categoria);
CREATE INDEX IF NOT EXISTS idx_temas_keywords ON quipu_categorias USING GIN(keywords);
CREATE INDEX IF NOT EXISTS idx_cliente_temas_cliente ON quipu_cliente_categorias(cliente_id);
CREATE INDEX IF NOT EXISTS idx_cliente_temas_prioridad ON quipu_cliente_categorias(cliente_id, prioridad);

-- Seed de 248 temas desde categorias.json
INSERT INTO quipu_categorias (nombre, orden) VALUES
('Aborto y Derechos Reproductivos', 1),
('Acoso y Abuso', 2),
('Activismo', 3),
('Acuerdos Comerciales', 4),
('Adopción', 5),
('Agricultura y Agroindustria', 6),
('Agua y Saneamiento', 7),
('Alcohol Ilegal y Actividades Ilícitas', 8),
('Analítica de Datos', 9),
('Antibióticos y Resistencia', 10),
('Antropología', 11),
('Aplicaciones de Transporte Urbano', 12),
('Aprendizaje en Línea', 13),
('Arqueología', 14),
('Arquitectura y Diseño', 15),
('Arrendamiento de Vehículos', 16),
('Arte Contemporáneo', 17),
('Artes y Cultura', 18),
('Astronomía y Exploración Espacial', 19),
('Automatización y Futuro del Trabajo', 20),
('Aviación', 21),
('Ayuda Humanitaria', 22),
('Banca Ética', 23),
('Bebidas', 24),
('Bienes Raíces', 25),
('Big Data', 26),
('Biodiversidad', 27),
('Biología y Genética', 28),
('Biotecnología', 29),
('Blanqueo de Capitales', 30),
('Blockchain y Criptomonedas', 31),
('Bullying y Acoso Escolar', 32),
('Cambio Climático y Medio Ambiente', 33),
('Cibercrimen', 34),
('Ciberseguridad', 35),
('Ciberseguridad Nacional', 36),
('Cine', 37),
('Clima', 38),
('Colonialismo y Postcolonialismo', 39),
('Comercio Electrónico', 40),
('Comercio Internacional', 41),
('Comercio Justo', 42),
('Computación Cuántica', 43),
('Comunicación Corporativa y Relaciones Públicas', 44),
('Conflictos Internacionales', 45),
('Conservación de Especies', 46),
('Construcción', 47),
('Consultoría Empresarial', 48),
('Consumo de Alcohol y Bebidas Alcohólicas', 49),
('Consumo Responsable', 50),
('Contaminación', 51),
('Cooperación con el Sector Privado', 52),
('Cooperación Internacional', 53),
('Cooperativas', 54),
('Corrupción y Transparencia', 55),
('Crianza', 56),
('Crimen Organizado', 57),
('Crowdfunding', 58),
('Deforestación', 59),
('Deportes', 60),
('Derecho Internacional', 61),
('Derechos Humanos', 62),
('Derechos LGBTQ+', 63),
('Desarrollo Social', 64),
('Desarrollo Urbano', 65),
('Desertificación', 66),
('Diversidad, Equidad e Inclusión (DEI)', 67),
('Diversificación Empresarial', 68),
('Economía Circular', 69),
('Economía Colaborativa', 70),
('Economía Digital', 71),
('Economía Informal', 72),
('Economía Local', 73),
('Economía Social', 74),
('Ecoturismo', 75),
('Educación Continua', 76),
('Educación Escolar', 77),
('Educación Especial', 78),
('Educación Infantil', 79),
('Educación Sexual', 80),
('Educación Superior', 81),
('Elecciones y Sistemas Electorales', 82),
('Energía Eléctrica', 83),
('Energías Renovables', 84),
('Enfermedades Raras', 85),
('Entretenimiento Audiovisual y Plataformas de Streaming', 86),
('Epidemias y Pandemias', 87),
('Espionaje y Inteligencia', 88),
('Evasión Fiscal', 89),
('Explotación Laboral', 90),
('Fabricación de Vehículos', 91),
('Familia y Relaciones', 92),
('Festivales Culturales', 93),
('Filantropía', 94),
('Filosofía y Ética', 95),
('Fitness y Bienestar', 96),
('Formación Profesional', 97),
('Fronteras y Territorios', 98),
('Fuerzas Armadas', 99),
('Física y Matemáticas', 100),
('Gastronomía', 101),
('Geología', 102),
('Geopolítica', 103),
('Gestión de Residuos Sólidos y Medio Ambiente', 104),
('Gestión Financiera', 105),
('Globalización', 106),
('Gobierno Corporativo', 107),
('Gobierno Regional y Local', 108),
('Gobierno y Administración Pública', 109),
('Hidrocarburos', 110),
('Higiene y Desinfección', 111),
('Historia', 112),
('Homeschooling', 113),
('Hotelería', 114),
('Huelgas y Protestas', 115),
('Idiomas y Multilingüismo', 116),
('Igualdad de Género', 117),
('Inclusión Financiera', 118),
('Industria 4.0', 119),
('Industria Alimentaria', 120),
('Industria Cosmética', 121),
('Industria de Alimentos y Restaurantes', 122),
('Industria de Defensa', 123),
('Industria de Entregas y Logística de Última Milla', 124),
('Industria Manufacturera', 125),
('Infancia y Derechos del Niño', 126),
('Inflación y Deflación', 127),
('Infraestructura Vial', 128),
('Infraestructura y Desarrollo Portuario', 129),
('Ingeniería Genética', 130),
('Inmobiliario', 131),
('Innovación Tecnológica', 132),
('Inteligencia Artificial', 133),
('Intercambio Cultural', 134),
('Internet de las Cosas (IoT)', 135),
('Inversión Socialmente Responsable', 136),
('Investigación Científica', 137),
('Justicia y Sistema Judicial', 138),
('Juventud', 139),
('Legislación de Transporte', 140),
('Literatura y Crítica Literaria', 141),
('Lobby y Grupos de Interés', 142),
('Logística Portuaria y Marítima', 143),
('Logística y Transporte', 144),
('Machine Learning', 145),
('Maternidad y Paternidad', 146),
('Matrimonio y Divorcio', 147),
('Medicina Alternativa', 148),
('Medicina Regenerativa', 149),
('Mercado Financiero y Bolsa de Valores', 150),
('Mercado Laboral', 151),
('Meteorología', 152),
('Microfinanzas', 153),
('Migración y Refugiados', 154),
('Minería', 155),
('Movilidad Sostenible', 156),
('Movimientos Sociales', 157),
('Música', 158),
('Nacionalismo', 159),
('Nanotecnología', 160),
('Narcotráfico', 161),
('Negociaciones Colectivas', 162),
('Nutrición y Alimentación Saludable', 163),
('Nutrición y Dietas', 164),
('Oceanografía', 165),
('ONG y Organizaciones Sin Fines de Lucro', 166),
('Otros', 167),
('Paraísos Fiscales', 168),
('Parques Nacionales', 169),
('Partidos Políticos', 170),
('Patrimonio Cultural', 171),
('Pensiones', 172),
('Pesca', 173),
('Planificación Familiar', 174),
('Pobreza y Desigualdad', 175),
('Política', 176),
('Política Internacional', 177),
('Política Monetaria', 178),
('Prevención y Gestión de Desastres', 179),
('Privacidad y Protección de Datos', 180),
('Productos de Limpieza e Higiene Personal', 181),
('Programas Sociales', 182),
('Propiedad Intelectual', 183),
('Prácticas Corporativas y Responsabilidad Empresarial', 184),
('Psicología', 185),
('Química', 186),
('Realidad Virtual y Aumentada', 187),
('Reciclaje', 188),
('Reclutamiento y Contratación de Personal', 189),
('Recursos Naturales', 190),
('Redes 5G', 191),
('Redes Sociales', 192),
('Reforma Penitenciaria', 193),
('Reformas Laborales', 194),
('Regulaciones Gubernamentales', 195),
('Regulaciones y Protección al Consumidor', 196),
('Regulación de Productos Alimenticios', 197),
('Relaciones Diplomáticas', 198),
('Religión y Espiritualidad', 199),
('Reparto de Alimentos y Bebidas', 200),
('Reproducción Asistida', 201),
('Responsabilidad Social Corporativa', 202),
('Retail', 203),
('Robótica', 204),
('Salud Mental', 205),
('Salud Pública y Sistema de Salud', 206),
('Salud Reproductiva', 207),
('Salud y Farmacéutica', 208),
('Saneamiento', 209),
('Seguridad Alimentaria', 210),
('Seguridad Laboral en la Industria de Restaurantes', 211),
('Seguridad Nacional', 212),
('Seguridad Pública', 213),
('Seguridad Vial', 214),
('Seguros', 215),
('Servicios Financieros', 216),
('Sexualidad', 217),
('Sindicalismo y Derechos Laborales', 218),
('Sindicatos', 219),
('Smart Cities', 220),
('Sociología', 221),
('Sostenibilidad Empresarial', 222),
('Startups y Emprendimiento', 223),
('Supercomputación', 224),
('Tabaco y Regulación', 225),
('Teatro y Artes Escénicas', 226),
('Tecnología y Transformación Digital', 227),
('Telecomunicaciones', 228),
('Teletrabajo', 229),
('Tercera Edad y Envejecimiento', 230),
('Terrorismo y Contrainsurgencia', 231),
('Trabajo Infantil', 232),
('Transporte Ferroviario', 233),
('Transporte Marítimo', 234),
('Transporte Público', 235),
('Transporte y Movilidad Urbana', 236),
('Trasplantes', 237),
('Trata de Personas', 238),
('Turismo y Viajes', 239),
('Urbanismo', 240),
('Vacunas', 241),
('Vehículos Autónomos', 242),
('Videojuegos y eSports', 243),
('Violencia de Género', 244),
('Vivienda Social', 245),
('Voluntariado', 246),
('Ética Empresarial', 247)
ON CONFLICT (nombre) DO NOTHING;
