-- =====================================================
-- Migración: Actualizar quipu_categorias_promesas con 247 categorías
-- Reemplaza las 15 categorías genéricas con las 247 específicas
-- =====================================================

-- Eliminar las categorías antiguas (las 15 originales)
DELETE FROM quipu_categorias_promesas;

-- Colores cíclicos para asignar a las categorías
-- Estos se repiten cada 15 categorías
-- #3B82F6, #EF4444, #10B981, #6366F1, #F59E0B,
-- #8B5CF6, #22C55E, #14B8A6, #EC4899, #06B6D4,
-- #F97316, #84CC16, #A855F7, #F43F5E, #64748B

-- Insertar las 247 categorías nuevas
-- nombre: clave normalizada (minúsculas, sin acentos, espacios -> _)
-- nombre_display: nombre original con espacios y acentos
INSERT INTO quipu_categorias_promesas (nombre, nombre_display, icono, color, orden) VALUES
('aborto_y_derechos_reproductivos', 'Aborto y Derechos Reproductivos', 'tag', '#3B82F6', 1),
('acoso_y_abuso', 'Acoso y Abuso', 'tag', '#EF4444', 2),
('activismo', 'Activismo', 'tag', '#10B981', 3),
('acuerdos_comerciales', 'Acuerdos Comerciales', 'tag', '#6366F1', 4),
('adopcion', 'Adopción', 'tag', '#F59E0B', 5),
('agricultura_y_agroindustria', 'Agricultura y Agroindustria', 'tag', '#8B5CF6', 6),
('agua_y_saneamiento', 'Agua y Saneamiento', 'tag', '#22C55E', 7),
('alcohol_ilegal_y_actividades_ilicitas', 'Alcohol Ilegal y Actividades Ilícitas', 'tag', '#14B8A6', 8),
('analitica_de_datos', 'Analítica de Datos', 'tag', '#EC4899', 9),
('antibioticos_y_resistencia', 'Antibióticos y Resistencia', 'tag', '#06B6D4', 10),
('antropologia', 'Antropología', 'tag', '#F97316', 11),
('aplicaciones_de_transporte_urbano', 'Aplicaciones de Transporte Urbano', 'tag', '#84CC16', 12),
('aprendizaje_en_linea', 'Aprendizaje en Línea', 'tag', '#A855F7', 13),
('arqueologia', 'Arqueología', 'tag', '#F43F5E', 14),
('arquitectura_y_diseno', 'Arquitectura y Diseño', 'tag', '#64748B', 15),
('arrendamiento_de_vehiculos', 'Arrendamiento de Vehículos', 'tag', '#3B82F6', 16),
('arte_contemporaneo', 'Arte Contemporáneo', 'tag', '#EF4444', 17),
('artes_y_cultura', 'Artes y Cultura', 'tag', '#10B981', 18),
('astronomia_y_exploracion_espacial', 'Astronomía y Exploración Espacial', 'tag', '#6366F1', 19),
('automatizacion_y_futuro_del_trabajo', 'Automatización y Futuro del Trabajo', 'tag', '#F59E0B', 20),
('aviacion', 'Aviación', 'tag', '#8B5CF6', 21),
('ayuda_humanitaria', 'Ayuda Humanitaria', 'tag', '#22C55E', 22),
('banca_etica', 'Banca Ética', 'tag', '#14B8A6', 23),
('bebidas', 'Bebidas', 'tag', '#EC4899', 24),
('bienes_raices', 'Bienes Raíces', 'tag', '#06B6D4', 25),
('big_data', 'Big Data', 'tag', '#F97316', 26),
('biodiversidad', 'Biodiversidad', 'tag', '#84CC16', 27),
('biologia_y_genetica', 'Biología y Genética', 'tag', '#A855F7', 28),
('biotecnologia', 'Biotecnología', 'tag', '#F43F5E', 29),
('blanqueo_de_capitales', 'Blanqueo de Capitales', 'tag', '#64748B', 30),
('blockchain_y_criptomonedas', 'Blockchain y Criptomonedas', 'tag', '#3B82F6', 31),
('bullying_y_acoso_escolar', 'Bullying y Acoso Escolar', 'tag', '#EF4444', 32),
('cambio_climatico_y_medio_ambiente', 'Cambio Climático y Medio Ambiente', 'tag', '#10B981', 33),
('cibercrimen', 'Cibercrimen', 'tag', '#6366F1', 34),
('ciberseguridad', 'Ciberseguridad', 'tag', '#F59E0B', 35),
('ciberseguridad_nacional', 'Ciberseguridad Nacional', 'tag', '#8B5CF6', 36),
('cine', 'Cine', 'tag', '#22C55E', 37),
('clima', 'Clima', 'tag', '#14B8A6', 38),
('colonialismo_y_postcolonialismo', 'Colonialismo y Postcolonialismo', 'tag', '#EC4899', 39),
('comercio_electronico', 'Comercio Electrónico', 'tag', '#06B6D4', 40),
('comercio_internacional', 'Comercio Internacional', 'tag', '#F97316', 41),
('comercio_justo', 'Comercio Justo', 'tag', '#84CC16', 42),
('computacion_cuantica', 'Computación Cuántica', 'tag', '#A855F7', 43),
('comunicacion_corporativa_y_relaciones_publicas', 'Comunicación Corporativa y Relaciones Públicas', 'tag', '#F43F5E', 44),
('conflictos_internacionales', 'Conflictos Internacionales', 'tag', '#64748B', 45),
('conservacion_de_especies', 'Conservación de Especies', 'tag', '#3B82F6', 46),
('construccion', 'Construcción', 'tag', '#EF4444', 47),
('consultoria_empresarial', 'Consultoría Empresarial', 'tag', '#10B981', 48),
('consumo_de_alcohol_y_bebidas_alcoholicas', 'Consumo de Alcohol y Bebidas Alcohólicas', 'tag', '#6366F1', 49),
('consumo_responsable', 'Consumo Responsable', 'tag', '#F59E0B', 50),
('contaminacion', 'Contaminación', 'tag', '#8B5CF6', 51),
('cooperacion_con_el_sector_privado', 'Cooperación con el Sector Privado', 'tag', '#22C55E', 52),
('cooperacion_internacional', 'Cooperación Internacional', 'tag', '#14B8A6', 53),
('cooperativas', 'Cooperativas', 'tag', '#EC4899', 54),
('corrupcion_y_transparencia', 'Corrupción y Transparencia', 'tag', '#06B6D4', 55),
('crianza', 'Crianza', 'tag', '#F97316', 56),
('crimen_organizado', 'Crimen Organizado', 'tag', '#84CC16', 57),
('crowdfunding', 'Crowdfunding', 'tag', '#A855F7', 58),
('deforestacion', 'Deforestación', 'tag', '#F43F5E', 59),
('deportes', 'Deportes', 'tag', '#64748B', 60),
('derecho_internacional', 'Derecho Internacional', 'tag', '#3B82F6', 61),
('derechos_humanos', 'Derechos Humanos', 'tag', '#EF4444', 62),
('derechos_lgbtq+', 'Derechos LGBTQ+', 'tag', '#10B981', 63),
('desarrollo_social', 'Desarrollo Social', 'tag', '#6366F1', 64),
('desarrollo_urbano', 'Desarrollo Urbano', 'tag', '#F59E0B', 65),
('desertificacion', 'Desertificación', 'tag', '#8B5CF6', 66),
('diversidad,_equidad_e_inclusion_(dei)', 'Diversidad, Equidad e Inclusión (DEI)', 'tag', '#22C55E', 67),
('diversificacion_empresarial', 'Diversificación Empresarial', 'tag', '#14B8A6', 68),
('economia_circular', 'Economía Circular', 'tag', '#EC4899', 69),
('economia_colaborativa', 'Economía Colaborativa', 'tag', '#06B6D4', 70),
('economia_digital', 'Economía Digital', 'tag', '#F97316', 71),
('economia_informal', 'Economía Informal', 'tag', '#84CC16', 72),
('economia_local', 'Economía Local', 'tag', '#A855F7', 73),
('economia_social', 'Economía Social', 'tag', '#F43F5E', 74),
('ecoturismo', 'Ecoturismo', 'tag', '#64748B', 75),
('educacion_continua', 'Educación Continua', 'tag', '#3B82F6', 76),
('educacion_escolar', 'Educación Escolar', 'tag', '#EF4444', 77),
('educacion_especial', 'Educación Especial', 'tag', '#10B981', 78),
('educacion_infantil', 'Educación Infantil', 'tag', '#6366F1', 79),
('educacion_sexual', 'Educación Sexual', 'tag', '#F59E0B', 80),
('educacion_superior', 'Educación Superior', 'tag', '#8B5CF6', 81),
('elecciones_y_sistemas_electorales', 'Elecciones y Sistemas Electorales', 'tag', '#22C55E', 82),
('energia_electrica', 'Energía Eléctrica', 'tag', '#14B8A6', 83),
('energias_renovables', 'Energías Renovables', 'tag', '#EC4899', 84),
('enfermedades_raras', 'Enfermedades Raras', 'tag', '#06B6D4', 85),
('entretenimiento_audiovisual_y_plataformas_de_streaming', 'Entretenimiento Audiovisual y Plataformas de Streaming', 'tag', '#F97316', 86),
('epidemias_y_pandemias', 'Epidemias y Pandemias', 'tag', '#84CC16', 87),
('espionaje_y_inteligencia', 'Espionaje y Inteligencia', 'tag', '#A855F7', 88),
('evasion_fiscal', 'Evasión Fiscal', 'tag', '#F43F5E', 89),
('explotacion_laboral', 'Explotación Laboral', 'tag', '#64748B', 90),
('fabricacion_de_vehiculos', 'Fabricación de Vehículos', 'tag', '#3B82F6', 91),
('familia_y_relaciones', 'Familia y Relaciones', 'tag', '#EF4444', 92),
('festivales_culturales', 'Festivales Culturales', 'tag', '#10B981', 93),
('filantropia', 'Filantropía', 'tag', '#6366F1', 94),
('filosofia_y_etica', 'Filosofía y Ética', 'tag', '#F59E0B', 95),
('fitness_y_bienestar', 'Fitness y Bienestar', 'tag', '#8B5CF6', 96),
('formacion_profesional', 'Formación Profesional', 'tag', '#22C55E', 97),
('fronteras_y_territorios', 'Fronteras y Territorios', 'tag', '#14B8A6', 98),
('fuerzas_armadas', 'Fuerzas Armadas', 'tag', '#EC4899', 99),
('fisica_y_matematicas', 'Física y Matemáticas', 'tag', '#06B6D4', 100),
('gastronomia', 'Gastronomía', 'tag', '#F97316', 101),
('geologia', 'Geología', 'tag', '#84CC16', 102),
('geopolitica', 'Geopolítica', 'tag', '#A855F7', 103),
('gestion_de_residuos_solidos_y_medio_ambiente', 'Gestión de Residuos Sólidos y Medio Ambiente', 'tag', '#F43F5E', 104),
('gestion_financiera', 'Gestión Financiera', 'tag', '#64748B', 105),
('globalizacion', 'Globalización', 'tag', '#3B82F6', 106),
('gobierno_corporativo', 'Gobierno Corporativo', 'tag', '#EF4444', 107),
('gobierno_regional_y_local', 'Gobierno Regional y Local', 'tag', '#10B981', 108),
('gobierno_y_administracion_publica', 'Gobierno y Administración Pública', 'tag', '#6366F1', 109),
('hidrocarburos', 'Hidrocarburos', 'tag', '#F59E0B', 110),
('higiene_y_desinfeccion', 'Higiene y Desinfección', 'tag', '#8B5CF6', 111),
('historia', 'Historia', 'tag', '#22C55E', 112),
('homeschooling', 'Homeschooling', 'tag', '#14B8A6', 113),
('hoteleria', 'Hotelería', 'tag', '#EC4899', 114),
('huelgas_y_protestas', 'Huelgas y Protestas', 'tag', '#06B6D4', 115),
('idiomas_y_multilinguismo', 'Idiomas y Multilingüismo', 'tag', '#F97316', 116),
('igualdad_de_genero', 'Igualdad de Género', 'tag', '#84CC16', 117),
('inclusion_financiera', 'Inclusión Financiera', 'tag', '#A855F7', 118),
('industria_4.0', 'Industria 4.0', 'tag', '#F43F5E', 119),
('industria_alimentaria', 'Industria Alimentaria', 'tag', '#64748B', 120),
('industria_cosmetica', 'Industria Cosmética', 'tag', '#3B82F6', 121),
('industria_de_alimentos_y_restaurantes', 'Industria de Alimentos y Restaurantes', 'tag', '#EF4444', 122),
('industria_de_defensa', 'Industria de Defensa', 'tag', '#10B981', 123),
('industria_de_entregas_y_logistica_de_ultima_milla', 'Industria de Entregas y Logística de Última Milla', 'tag', '#6366F1', 124),
('industria_manufacturera', 'Industria Manufacturera', 'tag', '#F59E0B', 125),
('infancia_y_derechos_del_nino', 'Infancia y Derechos del Niño', 'tag', '#8B5CF6', 126),
('inflacion_y_deflacion', 'Inflación y Deflación', 'tag', '#22C55E', 127),
('infraestructura_vial', 'Infraestructura Vial', 'tag', '#14B8A6', 128),
('infraestructura_y_desarrollo_portuario', 'Infraestructura y Desarrollo Portuario', 'tag', '#EC4899', 129),
('ingenieria_genetica', 'Ingeniería Genética', 'tag', '#06B6D4', 130),
('inmobiliario', 'Inmobiliario', 'tag', '#F97316', 131),
('innovacion_tecnologica', 'Innovación Tecnológica', 'tag', '#84CC16', 132),
('inteligencia_artificial', 'Inteligencia Artificial', 'tag', '#A855F7', 133),
('intercambio_cultural', 'Intercambio Cultural', 'tag', '#F43F5E', 134),
('internet_de_las_cosas_(iot)', 'Internet de las Cosas (IoT)', 'tag', '#64748B', 135),
('inversion_socialmente_responsable', 'Inversión Socialmente Responsable', 'tag', '#3B82F6', 136),
('investigacion_cientifica', 'Investigación Científica', 'tag', '#EF4444', 137),
('justicia_y_sistema_judicial', 'Justicia y Sistema Judicial', 'tag', '#10B981', 138),
('juventud', 'Juventud', 'tag', '#6366F1', 139),
('legislacion_de_transporte', 'Legislación de Transporte', 'tag', '#F59E0B', 140),
('literatura_y_critica_literaria', 'Literatura y Crítica Literaria', 'tag', '#8B5CF6', 141),
('lobby_y_grupos_de_interes', 'Lobby y Grupos de Interés', 'tag', '#22C55E', 142),
('logistica_portuaria_y_maritima', 'Logística Portuaria y Marítima', 'tag', '#14B8A6', 143),
('logistica_y_transporte', 'Logística y Transporte', 'tag', '#EC4899', 144),
('machine_learning', 'Machine Learning', 'tag', '#06B6D4', 145),
('maternidad_y_paternidad', 'Maternidad y Paternidad', 'tag', '#F97316', 146),
('matrimonio_y_divorcio', 'Matrimonio y Divorcio', 'tag', '#84CC16', 147),
('medicina_alternativa', 'Medicina Alternativa', 'tag', '#A855F7', 148),
('medicina_regenerativa', 'Medicina Regenerativa', 'tag', '#F43F5E', 149),
('mercado_financiero_y_bolsa_de_valores', 'Mercado Financiero y Bolsa de Valores', 'tag', '#64748B', 150),
('mercado_laboral', 'Mercado Laboral', 'tag', '#3B82F6', 151),
('meteorologia', 'Meteorología', 'tag', '#EF4444', 152),
('microfinanzas', 'Microfinanzas', 'tag', '#10B981', 153),
('migracion_y_refugiados', 'Migración y Refugiados', 'tag', '#6366F1', 154),
('mineria', 'Minería', 'tag', '#F59E0B', 155),
('movilidad_sostenible', 'Movilidad Sostenible', 'tag', '#8B5CF6', 156),
('movimientos_sociales', 'Movimientos Sociales', 'tag', '#22C55E', 157),
('musica', 'Música', 'tag', '#14B8A6', 158),
('nacionalismo', 'Nacionalismo', 'tag', '#EC4899', 159),
('nanotecnologia', 'Nanotecnología', 'tag', '#06B6D4', 160),
('narcotrafico', 'Narcotráfico', 'tag', '#F97316', 161),
('negociaciones_colectivas', 'Negociaciones Colectivas', 'tag', '#84CC16', 162),
('nutricion_y_alimentacion_saludable', 'Nutrición y Alimentación Saludable', 'tag', '#A855F7', 163),
('nutricion_y_dietas', 'Nutrición y Dietas', 'tag', '#F43F5E', 164),
('oceanografia', 'Oceanografía', 'tag', '#64748B', 165),
('ong_y_organizaciones_sin_fines_de_lucro', 'ONG y Organizaciones Sin Fines de Lucro', 'tag', '#3B82F6', 166),
('otros', 'Otros', 'tag', '#EF4444', 167),
('paraisos_fiscales', 'Paraísos Fiscales', 'tag', '#10B981', 168),
('parques_nacionales', 'Parques Nacionales', 'tag', '#6366F1', 169),
('partidos_politicos', 'Partidos Políticos', 'tag', '#F59E0B', 170),
('patrimonio_cultural', 'Patrimonio Cultural', 'tag', '#8B5CF6', 171),
('pensiones', 'Pensiones', 'tag', '#22C55E', 172),
('pesca', 'Pesca', 'tag', '#14B8A6', 173),
('planificacion_familiar', 'Planificación Familiar', 'tag', '#EC4899', 174),
('pobreza_y_desigualdad', 'Pobreza y Desigualdad', 'tag', '#06B6D4', 175),
('politica', 'Política', 'tag', '#F97316', 176),
('politica_internacional', 'Política Internacional', 'tag', '#84CC16', 177),
('politica_monetaria', 'Política Monetaria', 'tag', '#A855F7', 178),
('prevencion_y_gestion_de_desastres', 'Prevención y Gestión de Desastres', 'tag', '#F43F5E', 179),
('privacidad_y_proteccion_de_datos', 'Privacidad y Protección de Datos', 'tag', '#64748B', 180),
('productos_de_limpieza_e_higiene_personal', 'Productos de Limpieza e Higiene Personal', 'tag', '#3B82F6', 181),
('programas_sociales', 'Programas Sociales', 'tag', '#EF4444', 182),
('propiedad_intelectual', 'Propiedad Intelectual', 'tag', '#10B981', 183),
('practicas_corporativas_y_responsabilidad_empresarial', 'Prácticas Corporativas y Responsabilidad Empresarial', 'tag', '#6366F1', 184),
('psicologia', 'Psicología', 'tag', '#F59E0B', 185),
('quimica', 'Química', 'tag', '#8B5CF6', 186),
('realidad_virtual_y_aumentada', 'Realidad Virtual y Aumentada', 'tag', '#22C55E', 187),
('reciclaje', 'Reciclaje', 'tag', '#14B8A6', 188),
('reclutamiento_y_contratacion_de_personal', 'Reclutamiento y Contratación de Personal', 'tag', '#EC4899', 189),
('recursos_naturales', 'Recursos Naturales', 'tag', '#06B6D4', 190),
('redes_5g', 'Redes 5G', 'tag', '#F97316', 191),
('redes_sociales', 'Redes Sociales', 'tag', '#84CC16', 192),
('reforma_penitenciaria', 'Reforma Penitenciaria', 'tag', '#A855F7', 193),
('reformas_laborales', 'Reformas Laborales', 'tag', '#F43F5E', 194),
('regulaciones_gubernamentales', 'Regulaciones Gubernamentales', 'tag', '#64748B', 195),
('regulaciones_y_proteccion_al_consumidor', 'Regulaciones y Protección al Consumidor', 'tag', '#3B82F6', 196),
('regulacion_de_productos_alimenticios', 'Regulación de Productos Alimenticios', 'tag', '#EF4444', 197),
('relaciones_diplomaticas', 'Relaciones Diplomáticas', 'tag', '#10B981', 198),
('religion_y_espiritualidad', 'Religión y Espiritualidad', 'tag', '#6366F1', 199),
('reparto_de_alimentos_y_bebidas', 'Reparto de Alimentos y Bebidas', 'tag', '#F59E0B', 200),
('reproduccion_asistida', 'Reproducción Asistida', 'tag', '#8B5CF6', 201),
('responsabilidad_social_corporativa', 'Responsabilidad Social Corporativa', 'tag', '#22C55E', 202),
('retail', 'Retail', 'tag', '#14B8A6', 203),
('robotica', 'Robótica', 'tag', '#EC4899', 204),
('salud_mental', 'Salud Mental', 'tag', '#06B6D4', 205),
('salud_publica_y_sistema_de_salud', 'Salud Pública y Sistema de Salud', 'tag', '#F97316', 206),
('salud_reproductiva', 'Salud Reproductiva', 'tag', '#84CC16', 207),
('salud_y_farmaceutica', 'Salud y Farmacéutica', 'tag', '#A855F7', 208),
('saneamiento', 'Saneamiento', 'tag', '#F43F5E', 209),
('seguridad_alimentaria', 'Seguridad Alimentaria', 'tag', '#64748B', 210),
('seguridad_laboral_en_la_industria_de_restaurantes', 'Seguridad Laboral en la Industria de Restaurantes', 'tag', '#3B82F6', 211),
('seguridad_nacional', 'Seguridad Nacional', 'tag', '#EF4444', 212),
('seguridad_publica', 'Seguridad Pública', 'tag', '#10B981', 213),
('seguridad_vial', 'Seguridad Vial', 'tag', '#6366F1', 214),
('seguros', 'Seguros', 'tag', '#F59E0B', 215),
('servicios_financieros', 'Servicios Financieros', 'tag', '#8B5CF6', 216),
('sexualidad', 'Sexualidad', 'tag', '#22C55E', 217),
('sindicalismo_y_derechos_laborales', 'Sindicalismo y Derechos Laborales', 'tag', '#14B8A6', 218),
('sindicatos', 'Sindicatos', 'tag', '#EC4899', 219),
('smart_cities', 'Smart Cities', 'tag', '#06B6D4', 220),
('sociologia', 'Sociología', 'tag', '#F97316', 221),
('sostenibilidad_empresarial', 'Sostenibilidad Empresarial', 'tag', '#84CC16', 222),
('startups_y_emprendimiento', 'Startups y Emprendimiento', 'tag', '#A855F7', 223),
('supercomputacion', 'Supercomputación', 'tag', '#F43F5E', 224),
('tabaco_y_regulacion', 'Tabaco y Regulación', 'tag', '#64748B', 225),
('teatro_y_artes_escenicas', 'Teatro y Artes Escénicas', 'tag', '#3B82F6', 226),
('tecnologia_y_transformacion_digital', 'Tecnología y Transformación Digital', 'tag', '#EF4444', 227),
('telecomunicaciones', 'Telecomunicaciones', 'tag', '#10B981', 228),
('teletrabajo', 'Teletrabajo', 'tag', '#6366F1', 229),
('tercera_edad_y_envejecimiento', 'Tercera Edad y Envejecimiento', 'tag', '#F59E0B', 230),
('terrorismo_y_contrainsurgencia', 'Terrorismo y Contrainsurgencia', 'tag', '#8B5CF6', 231),
('trabajo_infantil', 'Trabajo Infantil', 'tag', '#22C55E', 232),
('transporte_ferroviario', 'Transporte Ferroviario', 'tag', '#14B8A6', 233),
('transporte_maritimo', 'Transporte Marítimo', 'tag', '#EC4899', 234),
('transporte_publico', 'Transporte Público', 'tag', '#06B6D4', 235),
('transporte_y_movilidad_urbana', 'Transporte y Movilidad Urbana', 'tag', '#F97316', 236),
('trasplantes', 'Trasplantes', 'tag', '#84CC16', 237),
('trata_de_personas', 'Trata de Personas', 'tag', '#A855F7', 238),
('turismo_y_viajes', 'Turismo y Viajes', 'tag', '#F43F5E', 239),
('urbanismo', 'Urbanismo', 'tag', '#64748B', 240),
('vacunas', 'Vacunas', 'tag', '#3B82F6', 241),
('vehiculos_autonomos', 'Vehículos Autónomos', 'tag', '#EF4444', 242),
('videojuegos_y_esports', 'Videojuegos y eSports', 'tag', '#10B981', 243),
('violencia_de_genero', 'Violencia de Género', 'tag', '#6366F1', 244),
('vivienda_social', 'Vivienda Social', 'tag', '#F59E0B', 245),
('voluntariado', 'Voluntariado', 'tag', '#8B5CF6', 246),
('etica_empresarial', 'Ética Empresarial', 'tag', '#22C55E', 247)
ON CONFLICT (nombre) DO UPDATE SET
  nombre_display = EXCLUDED.nombre_display,
  icono = EXCLUDED.icono,
  color = EXCLUDED.color,
  orden = EXCLUDED.orden;

-- Verificar el resultado
SELECT COUNT(*) as total_categorias FROM quipu_categorias_promesas;
